//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelSw.Wix.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanelSw.Wix.Extensions.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create container &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string ContainerError {
            get {
                return ResourceManager.GetString("ContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The InstallExecuteSequence table contains action &apos;{1}&apos; in between actions required for ExecuteCommand action &apos;{0}&apos;. Please schedule commands to execute after &apos;{0}&apos; or before &apos;Prepare{0}&apos;.
        /// </summary>
        internal static string ExecuteCommandSequence {
            get {
                return ResourceManager.GetString("ExecuteCommandSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveFolderEx element has a &apos;LongPathHandling&apos; attribute that collides with another aothored RemoveFolderEx.
        /// </summary>
        internal static string MismatchingRemoveFolderExLongPathHandling {
            get {
                return ResourceManager.GetString("MismatchingRemoveFolderExLongPathHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find ContainerTemplate element to create container &apos;{0}&apos; with..
        /// </summary>
        internal static string MissingContainerTemplate {
            get {
                return ResourceManager.GetString("MissingContainerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload &apos;{0}&apos; is larger than the maximal size set in ContainerTemplate, {1}.
        /// </summary>
        internal static string PayloadExceedsSize {
            get {
                return ResourceManager.GetString("PayloadExceedsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; of element &apos;{1}&apos; is only supported when using PanelSwWix4.Sdk. Replace all &apos;WixToolset.*&apos; package references with &apos;PanelSwWix4.*&apos;.
        /// </summary>
        internal static string PswWixAttribute {
            get {
                return ResourceManager.GetString("PswWixAttribute", resourceCulture);
            }
        }
    }
}
