#pragma once
class CSummaryStream
{
public:

	static HRESULT IsPackageX64();
	static HRESULT IsUserContext();

private:

	enum SummaryStreamProperties
	{
		SUMMARYSTREAM_PID_CODEPAGE = 1,
		SUMMARYSTREAM_PID_TITLE = 2,
		SUMMARYSTREAM_PID_SUBJECT = 3,
		SUMMARYSTREAM_PID_AUTHOR = 4,
		SUMMARYSTREAM_PID_KEYWORDS = 5,
		SUMMARYSTREAM_PID_COMMENTS = 6,
		SUMMARYSTREAM_PID_TEMPLATE = 7,
		SUMMARYSTREAM_PID_LASTAUTHOR = 8,
		SUMMARYSTREAM_PID_REVNUMBER = 9,
		SUMMARYSTREAM_PID_LASTPRINTED = 11,
		SUMMARYSTREAM_PID_CREATE_DTM = 12,
		SUMMARYSTREAM_PID_LASTSAVE_DTM = 13,
		SUMMARYSTREAM_PID_PAGECOUNT = 14,
		SUMMARYSTREAM_PID_WORDCOUNT = 15,
		SUMMARYSTREAM_PID_CHARCOUNT = 16,
		SUMMARYSTREAM_PID_APPNAME = 18,
		SUMMARYSTREAM_PID_SECURITY = 19
	};

	// See https://docs.microsoft.com/en-us/windows/win32/msi/word-count-summary
	enum SummaryStreamWordCount
	{
		WORD_COUNT_SHORT_NAMES = 1,
		WORD_COUNT_COMPRESSED = 2,
		WORD_COUNT_ADMIN_IMAGE = 4,
		WORD_COUNT_UAC_COMPLIANT = 8,
	};

	static HRESULT GetSummaryStreamProperty(SummaryStreamProperties iProperty, LPWSTR* pszValue);
	static HRESULT GetSummaryStreamProperty(SummaryStreamProperties iProperty, INT* piValue);
};
