<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="16.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup Condition="'$(DebuggableRelease)'=='true'">
    <DefineConstants>DEBUGGABLE_RELEASE;$(DefineConstants)</DefineConstants>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(DebuggableRelease)'=='true'">
    <ClCompile>
      <PreprocessorDefinitions>DEBUGGABLE_RELEASE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <Optimization>Disabled</Optimization>
      <WholeProgramOptimization>false</WholeProgramOptimization>
      <AdditionalOptions>/bigobj %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>DebugFull</GenerateDebugInformation>
      <LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
    </Link>
  </ItemDefinitionGroup>
</Project>
